export { createMessageId } from "./ids.js";
export {
  ACK_PROTOCOL_VERSION,
  AckType,
  ackStatusFromType,
  ackTypeFromStatus,
  compactAckPlaintext,
  conversationIsActivelyViewed,
  countUnread,
  formatUnreadBadge,
  isUnreadInbound,
  mergePersistedStatus,
  parseAckPlain,
  receiptRank,
  type ValidatedAck,
} from "./acks.js";
export {
  DEFAULT_TTL_MS,
  MAX_HOPS,
  MessageStatus,
  createMessage,
  isExpired,
  shouldStopForwarding,
  type CreateMessageInput,
  type HopMessage,
} from "./message.js";
export {
  ALLOWED_TRANSITIONS,
  IllegalStateTransitionError,
  canTransition,
  transition,
} from "./stateMachine.js";
export { ProcessedIdSet } from "./duplicates.js";
export { DEFAULT_RETRY_POLICY, nextBackoffMs, type RetryPolicy } from "./retry.js";
export {
  toEnvelope,
  type EncryptedEnvelope,
  type NetworkStatus,
  type SendResult,
  type Transport,
  type TransportId,
  type TransportRoute,
  type TransportRuntimeStatus,
} from "./transport.js";
export { LocalTransport } from "./localTransport.js";
export { InternetTransport, createInternetTransport } from "./internetTransport.js";
export type { HopHttpClient } from "./http.js";
export { createRelayTransport } from "./stubTransports.js";
export { createBluetoothTransport, BluetoothTransport, type BlePayloadPreparer } from "./bluetoothTransport.js";
export type {
  BleAdapterState,
  BleAuthorizationStatus,
  BleLink,
  BleLinkStatus,
  BlePeer,
  BleScanMode,
  BleSessionOptions,
} from "./bleLink.js";
export {
  createProductionAppTransportManager,
  assertProductionTransportSet,
  PRODUCTION_APP_TRANSPORT_IDS,
  FORBIDDEN_PRODUCTION_TRANSPORT_IDS,
} from "./appTransports.js";
export {
  describeTransportSelection,
  describeProofRoute,
  isSafeDiagnosticsText,
  type BleDiagnosticsSnapshot,
  type BleHandshakePhase,
  type BleDiagSendResult,
  type BleDiagAckResult,
  type BleDiagInboundResult,
  type TransportSelectionInfo,
  type TransportSelectionId,
} from "./bleDiagnostics.js";
export {
  BLE_DEFAULT_CHUNK_BYTES,
  BLE_FALLBACK_CHUNK_BYTES,
  BLE_MAX_ASSEMBLED_BYTES,
  BLE_MAX_CHUNK_PAYLOAD,
  BLE_MAX_FRAME_BYTES,
  BLE_REASSEMBLER_STALE_MS,
  BLE_SESSION_IDLE_MS,
  HOP_BLE_ACK_UUID,
  HOP_BLE_HANDSHAKE_UUID,
  HOP_BLE_INBOX_UUID,
  HOP_BLE_SERVICE_UUID,
  BleReassembler,
  advertiseLocalName,
  bytesToHex,
  chunkBytes,
  decodeEnvelope,
  decodeHandshake,
  displayNameFromAdvertisement,
  encodeEnvelope,
  encodeHandshake,
  hexToBytes,
  looksLikeHardwareId,
  newHandshakeNonce,
  safeNearbyDisplayName,
  sanitizeAdvertisementDiscoveryId,
  sanitizeUntrustedLabel,
  type BleHandshake,
} from "./bleCodec.js";
export {
  authenticatedNearbyPeer,
  conversationPreviewLine,
  conversationTransportStatus,
  formatMessageStatus,
  formatNetworkStatus,
  internetStatusAvailable,
  isFailedMessageStatus,
  isInFlightOutboundStatus,
  localDirectConversationId,
  nearbyPeerLabel,
  nearbyPeerPresence,
  rssiSignalBars,
  type ConversationRoute,
  type ConversationTransportInput,
  type ConversationTransportView,
  type NearbyPeerSnapshot,
} from "./conversationTransport.js";
export { TransportManager, defaultTransportManager, LIVE_TRANSPORT_PRIORITY, type QueueItem } from "./transportManager.js";
export {
  AckLayer,
  CanonicalLifecycle,
  MAX_OUTBOX_MESSAGES,
  ackLayerFromStatus,
  canonicalLifecycle,
  compareConversationMessages,
  compareMergeKey,
  compareSenderStream,
  isOutboxStatus,
  isTransportAcceptedStatus,
  sameLogicalIdentity,
  sortConversationMessages,
} from "./lifecycle.js";
export {
  HopSqliteStore,
  SCHEMA_SQL,
  type InboundReceiptRow,
  type OutboundAckRow,
  type OutboundRow,
  type SqliteDriver,
  type StoredConversation,
  type StoredMessage,
} from "./store.js";
export { MessageService, type MessageCrypto, type SendEventTextInput, type SendTextInput, type SendVoiceInput } from "./messageService.js";
export {
  CHAT_PAGE_SIZE,
  applyOptimisticSendFailure,
  clampComposerText,
  conversationPresenceLabel,
  formatBubbleTimestamp,
  formatInboxTimestamp,
  formatMessageStatusDescription,
  inboxActivityKey,
  isComposerSendable,
  isOptimisticPreSendStatus,
  isPinnedToLatest,
  isVisibleChatMessage,
  mergeChatWindow,
  paginateConversationMessages,
  shouldAutoScrollOnIncoming,
  shouldMarkConversationRead,
  sortInboxConversations,
  userFacingLoadError,
  userFacingSendError,
  type ChatPage,
  type ChatPageOptions,
  type InboxSortItem,
} from "./conversationUi.js";
export {
  LOCAL_AVATAR_COLORS,
  bluetoothStatusLabel,
  conversationHasUndeliveredOutbox,
  inboxThreadClearPolicy,
  isHardcodedActiveBluetoothLabel,
  messagesTabBadgeCount,
  messagesTabBadgeLabel,
  nearbyPeerSheetActions,
  nearbySheetOpensPeerThread,
  nearbySheetSendsMessage,
  nearbySheetUsesSafetyService,
  requestCardActionUsesSafetyService,
  requestCardActions,
  requestCardCopy,
  rssiPercentForDisplay,
  type InboxClearMode,
  type NearbySheetActionId,
  type RequestCardActionId,
} from "./uxPresentation.js";
export { isBoxedEnvelopePayload, refuseUnencryptedPayloadError, requirePeerRecipient } from "./sendGuards.js";
export {
  REPORT_CATEGORIES,
  SAFETY_MESSAGES,
  SafetyError,
  bleDebugExposesHardwareId,
  decideInbound,
  decideOutbound,
  decideQrContact,
  denySafety,
  deriveOperatingMode,
  eventEnabledAfterPrivacyChange,
  eventModeMayRun,
  mayCommitEventEnable,
  inboxVisibilityFor,
  inferRelationshipFromHistory,
  isBleDebugEnabled,
  isDiscoverableMode,
  isSafetyError,
  isUnsafeNearbyLabel,
  operatingModeAfterEventExpiry,
  parseReportCategory,
  planOperatingMode,
  privacyModeForDiscoverable,
  rememberDiscoverableMode,
  shouldNotifyFor,
  type InboxVisibility,
  type LocalReportRecord,
  type NearbyAudience,
  type NearbyOperatingMode,
  type OperatingModePlan,
  type PeerRelationship,
  type PeerSafetyRecord,
  type ReportCategory,
  type SafetyDecision,
  type SafetyDenialCode,
  type SafetyGate,
} from "./safety.js";
export { SafetyService } from "./safetyService.js";
export {
  HOP_QR_KIND,
  HOP_USERNAME_RE,
  assertHopQrHasNoSecrets,
  createHopInviteToken,
  decodeHopQrPayload,
  encodeHopQrPayload,
  hopQrContainsSecrets,
  hopQrModules,
  hopQrUri,
  normalizeHopUsername,
  type HopQrPayload,
} from "./hopQr.js";
export {
  DEFAULT_VOICE_CAPTION,
  DEFAULT_VOICE_CODEC,
  DEFAULT_VOICE_MIME,
  MAX_ENCRYPTED_PAYLOAD_BYTES,
  MAX_VOICE_AUDIO_B64_CHARS,
  MAX_VOICE_DURATION_MS,
  MICROPHONE_DENIED_MESSAGE,
  assertEncryptedPayloadSize,
  assertVoiceFitsBudget,
  estimateBoxedPayloadBytes,
  isEphemeralVoicePlaybackName,
  microphoneDeniedMessage,
  newEphemeralVoiceFileId,
  voiceAudioB64,
  withDecryptedPlain,
} from "./voice.js";
export { PublicKeyTofu, sqlitePeerTrustPersistence, type PeerTrustPersistence, type PeerTrustRecord, type PeerTrustState } from "./tofu.js";
export {
  IdentityError,
  assertIdentityPublishHasNoSecret,
  assertPublishedIdentityMatches,
  assertWellFormedPublishKey,
  decideIdentityPublish,
  identityPublishBody,
  isHttpConflict,
  loadOrCreateIdentity,
  publishIdentityIfAllowed,
  replaceIdentityExplicit,
  serverKeyLockedError,
  type IdentityErrorCode,
  type IdentityPublishAction,
  type SecretBackend,
} from "./identityLifecycle.js";
export { formatPersistedFingerprint, identityFingerprint } from "./fingerprint.js";
export {
  BLE_KEY_CHANGED_REFUSAL,
  HandshakeReplayGuard,
  bleSendRefusal,
  bleSessionStale,
} from "./bleGuard.js";
export {
  BLE_HANDSHAKE_CONTEXT,
  BLE_HANDSHAKE_DOWNGRADE,
  BLE_HANDSHAKE_MAX_SKEW_MS,
  BLE_HANDSHAKE_VERSION,
  BleHandshakeExchange,
  decodeAuthenticatedHandshake,
  decodeHandshakeAnnouncement,
  encodeAuthenticatedHandshake,
  encodeHandshakeAnnouncement,
  handshakeDowngradeReason,
  newAuthHandshakeNonce,
  parseHandshakeJson,
  verifyAuthenticatedHandshake,
  type BleAuthenticatedHandshake,
  type BleHandshakeAnnouncement,
  type HandshakeVerifyFailure,
  type HandshakeVerifyResult,
} from "./bleHandshake.js";
export { redactForLog, redactString, looksLikeSecretDump } from "./redact.js";
export { categorizeTransportFailure, type TransportFailureCategory } from "./transportErrors.js";
export {
  readWithSecretPolicy,
  shouldFailClosedSecretStore,
  writeWithSecretPolicy,
} from "./secretPolicy.js";
export {
  encodeAuthenticatedBleAck,
  isUnauthenticatedBleAck,
  verifyAuthenticatedBleAck,
  type BleAckExpectation,
  type BleLinkAck,
} from "./bleAck.js";
export {
  CRYPTO_BOX_ALG,
  CRYPTO_BOX_PUBLICKEYBYTES,
  decryptApplicationMessage,
  encryptApplicationMessage,
  generateIdentityKeyPair,
  isCryptoBoxPayload,
  isWellFormedBoxPublicKey,
  MAX_APPLICATION_TEXT_CHARS,
  parseCryptoBoxPayload,
  readySodium,
  setSodiumBackend,
  type ApplicationKind,
  type ApplicationPlaintext,
  type CryptoBoxPayload,
  type DecryptOptions,
  type HopSodium,
  type IdentityKeyPair,
} from "./cryptoBox.js";
export {
  CHATS_INBOX_SECTIONS,
  CONVERSATION_KINDS,
  EVENT_INVITE_STATUSES,
  EVENT_MEMBER_ROLES,
  EVENT_ROW_STATUSES,
  EVENT_SCHEDULE_STATUSES,
  EVENT_VISIBILITIES,
  MAX_EVENT_MEMBERS,
  MAX_EVENT_PENDING_INVITES,
  MAX_EVENT_START_AHEAD_MS,
  canAcceptEventInvite,
  canCancelInvite,
  canDeclineEventInvite,
  canEndEvent,
  canInviteToEvent,
  canJoinDiscoverableEvent,
  canLeaveEvent,
  canRemoveGuest,
  chatsInboxSectionForKind,
  discoverableDoesNotAutoJoin,
  endingEventArchivesChat,
  eventChatCanRead,
  eventChatCanSend,
  eventChatFanoutRecipients,
  eventListSection,
  eventRowStatus,
  eventScheduleStatus,
  normalizeConversationKind,
  removedMemberLosesFutureEventChat,
  shouldApplyDirectInboxSafety,
  type ChatsInboxSectionId,
  type ConversationKind,
  type EventInviteStatus,
  type EventMemberRole,
  type EventMembershipView,
  type EventRowStatus,
  type EventScheduleStatus,
  type EventVisibility,
} from "./events.js";
export { sendWithAckRetry, type AckAttempt } from "./ackRetry.js";
export {
  chooseNextHop,
  decideRelay,
  forwardedEnvelope,
  visitedPath,
  type RelayDecision,
  type RelayDropReason,
} from "./relayPolicy.js";
export { SimulatedNetwork, type SimEvent, type SimulatedNode } from "./simulatedNetwork.js";
export {
  assertSafeApiUrl,
  isLoopbackApiHost,
  isPrivateLanIpv4,
  resolveApiUrl,
  type ApiUrlPolicyOptions,
} from "./apiUrlPolicy.js";
